server:
  port: 8094
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: roncoo-pay-web-sample-shop
  mvc:
    view:
      prefix: /
      suffix: .jsp
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.3:8848
      
logging:
  config: classpath:logback.xml
