server:
  port: 8092
  servlet:
    session:
      timeout: 30m
    context-path: /roncoo-pay-web-gateway
spring:
  application:
    name: roncoo-pay-web-gateway
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.3:8848
            
      
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
